name: 'github-action-check-size-limit'
description: 'size-limit action'
author: 'Andres Alvarez <a.alvarez.sor@gmail.com>'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  is_monorepo:
    required: false
    description: 'denote if action is used in a Monorepo and thus install script should execute always on root instead of provided package/custom subdirectory'
    default: false
  github_token:
    required: true
    description: 'a github access token'
  install_script:
    required: false
    description: 'a custom npm script to install'
  build_script:
    required: false
    description: 'a custom npm script to build'
  clean_script:
    required: false
    description: 'a npm script to clean up build directory'
  skip_step:
    required: false
    description: 'which step to skip, either "install" or "build"'
  directory:
    required: false
    description: "a custom subdirectory"
  windows_verbatim_arguments:
    required: false
    description: "exec `size-limit` with the option `windowsVerbatimArguments`"
    default: true
  script:
    required: false
    default: "npx size-limit --json"
    description: "The script used to generate size-limit results"
runs:
  using: 'node20'
  main: 'dist/index.js'
