name: "size"

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run size
        uses: ./
        env:
          HUSKY: 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          install_script: "npm run setup:ci"
          clean_script: "npm run clean"
          build_script: "npm run build"
